version: "3.8"
services:
  wordcount:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /wordcount
    volumes:
      - ./backend:/app
    expose: [8080, 80]
    ports:
      - 8080:8080